const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const textFields = (n) => {
  const fields = {};
  for (let i = 1; i <= n; i++) {
    fields[`isi_artikel${i > 1 ? i : ''}`] = DataTypes.TEXT;
  }
  return fields;
};

const articleFields = {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
};

const models = {};

models.Acc = sequelize.define('acc', {
  admin_id: { type: DataTypes.INTEGER, primaryKey: true },
  kode_referal: DataTypes.STRING(80),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  admin_type_member: DataTypes.STRING(50),
  adminstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  admin_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  admin_validasi: DataTypes.STRING(250),
  admin_pesan_masuk: DataTypes.TEXT,
  admin_pesan_keluar: DataTypes.TEXT,
  admin_email: DataTypes.STRING(255),
  admin_password: DataTypes.STRING(255),
  admin_firstname: DataTypes.STRING(25),
  admin_lastname: DataTypes.TEXT,
  admin_ponsel: DataTypes.STRING(255),
  admin_skill1: DataTypes.STRING(250),
  admin_testimoni: DataTypes.STRING(250),
  admin_skill2: DataTypes.STRING(250),
  admin_typemember: DataTypes.STRING(255),
  admin_level: DataTypes.STRING(20),
  admin_upah_perproject: DataTypes.INTEGER(12),
  admin_avatar: DataTypes.STRING(255),
  kode_aktivasi: DataTypes.STRING(10),
  admin_shortbio: DataTypes.STRING(250),
  admin_username: DataTypes.STRING(25),
  admin_saldo: DataTypes.STRING(255),
  admin_deposit: DataTypes.INTEGER,
  admin_konfirmasi_bayar: DataTypes.STRING(250),
  admin_produk_laku: DataTypes.STRING(255),
  admin_point_reward: DataTypes.INTEGER,
  admin_longbio: DataTypes.STRING(300),
  admin_facebook: DataTypes.STRING(255),
  admin_twitter: DataTypes.STRING(255),
  admin_linkedin: DataTypes.STRING(255),
  admin_stumbleupon: DataTypes.STRING(255),
  admin_instagram: DataTypes.STRING(255),
  admin_googleplus: DataTypes.STRING(255),
  admin_website: DataTypes.STRING(255),
  admin_dob: DataTypes.DATEONLY,
  admin_profession: DataTypes.STRING(25),
  admin_gender: DataTypes.STRING(255),
  admin_maritialstatus: DataTypes.STRING(255),
  admin_address: DataTypes.TEXT,
  admin_backgroundpicture: DataTypes.STRING(255),
  admin_joindate: DataTypes.DATEONLY,
  admin_country: DataTypes.STRING(255),
  admin_skype: DataTypes.STRING(255),
  admin_github: DataTypes.STRING(255),
  admin_youtube: DataTypes.STRING(255),
  admin_vimeo: DataTypes.STRING(255),
  admin_freelancer_category: DataTypes.STRING(250),
  admin_gallery: DataTypes.STRING(255),
  admin_gallery_category: DataTypes.STRING(20),
  admin_company: DataTypes.STRING(25),
  admin_writer_category: { type: DataTypes.STRING(25), defaultValue: 'New member community' },
  admin_win_project: DataTypes.INTEGER,
  admin_debit: DataTypes.INTEGER,
  admin_selling: DataTypes.INTEGER,
  admin_saldo_total: DataTypes.STRING(50),
  admin_date: DataTypes.DATEONLY,
  admin_invoice: DataTypes.INTEGER(255),
  admin_yang_ingin_direkrut: DataTypes.STRING(50),
}, { timestamps: false, tableName: 'acc' });

const accArticleModels = [
  ['acc_assets', 'AccAssets', 'acc_assets_views', 'acc_assets_replies', 'acc_assets_semester', 'jenis_aset', 'nilai_harga'],
  ['acc_assets_pasif', 'AccAssetsPasif', 'acc_assets_pasif_views', 'acc_assets_pasif_replies', 'acc_assets_pasif_semester', 'jenis_aset', 'nilai_harga2'],
  ['acc_assets_tetap', 'AccAssetsTetap', 'acc_assets_tetap_views', 'acc_assets_tetap_replies', 'acc_assets_tetap_semester', 'jenis_aset', 'nilai_harga1'],
  ['acc_beban', 'AccBeban', 'acc_beban_views', 'acc_beban_replies', 'acc_beban_semester', 'jenis_aset', 'nilai_harga5'],
  ['acc_design', 'AccDesign', 'acc_design_views', 'acc_design_replies', 'acc_design_semester', 'jenis_aset', 'nilai_harga'],
  ['acc_hutang', 'AccHutang', 'acc_hutang_views', 'acc_hutang_replies', 'acc_hutang_semester', 'jenis_aset', 'nilai_harga3'],
  ['acc_modal', 'AccModal', 'acc_modal_views', 'acc_modal_replies', 'acc_modal_semester', 'jenis_aset', 'nilai_harga4'],
  ['acc_out', 'AccOut', 'acc_out_views', 'acc_out_replies', 'acc_out_semester', 'jenis_kas', 'jumlah'],
];

accArticleModels.forEach(([table, modelName, viewField, replyField, semesterField, jenisField, nilaiField]) => {
  const fields = {
    ...articleFields,
    [viewField]: DataTypes.INTEGER,
    [replyField]: DataTypes.INTEGER,
    [semesterField]: DataTypes.STRING(255),
    [jenisField]: DataTypes.TEXT,
    [nilaiField]: DataTypes.STRING(250),
  };
  models[modelName] = sequelize.define(modelName, fields, { timestamps: false, tableName: table });
});

models.AccIn = sequelize.define('acc_in', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  jumlah_masuk: DataTypes.STRING(250),
  invoice: DataTypes.STRING(250),
  kg: DataTypes.STRING(250),
  pcs: DataTypes.STRING(250),
  namabarang: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  jenis_kas: DataTypes.TEXT,
  jenis_pcs: DataTypes.STRING(13),
  jenis_kg: DataTypes.STRING(13),
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  acc_in_views: DataTypes.INTEGER,
  acc_in_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  acc_in_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'acc_in' });

models.AccInNonapp = sequelize.define('acc_in_nonapp', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  jumlah_masuk: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  jenis_kas: DataTypes.TEXT,
  jenis_pcs: DataTypes.STRING(13),
  jenis_kg: DataTypes.STRING(13),
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  acc_in_views: DataTypes.INTEGER,
  acc_in_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  acc_in_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'acc_in_nonapp' });

models.AccMarcom = sequelize.define('acc_marcom', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  acc_marcom_views: DataTypes.INTEGER,
  acc_marcom_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  acc_marcom_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'acc_marcom' });

module.exports = models;
