const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const textFields = (n) => {
  const fields = {};
  for (let i = 1; i <= n; i++) {
    fields[`isi_artikel${i > 1 ? i : ''}`] = DataTypes.TEXT;
  }
  return fields;
};

const articleBaseFields = {
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
};

const models = {};

models.Aparatur = sequelize.define('aparatur', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ...articleBaseFields,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(10),
  jabatan: DataTypes.TEXT,
  aparatur_views: DataTypes.INTEGER,
  aparatur_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  deskripsi: DataTypes.TEXT,
  handphone: DataTypes.TEXT,
  harga: DataTypes.TEXT,
  aparatur_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'aparatur' });

models.Biograph = sequelize.define('biograph', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  biograph_views: DataTypes.INTEGER,
  biograph_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  biograph_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'biograph' });

models.Development = sequelize.define('development', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  ...articleBaseFields,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  development_views: DataTypes.INTEGER,
  development_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  development_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'development' });

models.Gambar = sequelize.define('gambar', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  filename: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  gambar_views: DataTypes.INTEGER,
  gambar_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  gambar_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'gambar' });

models.GambarStock = sequelize.define('gambar_stock', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ...articleBaseFields,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  gambar_stock_views: DataTypes.INTEGER,
  gambar_stock_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  gambar_stock_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'gambar_stock' });

models.GambarUser = sequelize.define('gambar_user', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  ...articleBaseFields,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  gambar_user_views: DataTypes.INTEGER,
  gambar_user_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  gambar_user_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'gambar_user' });

models.Iklan = sequelize.define('iklan', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  alamat_perusahaan: DataTypes.TEXT,
  phone: DataTypes.STRING(80),
  catatan: DataTypes.TEXT,
  phone_mobile: DataTypes.STRING(80),
  nama_perusahaan: DataTypes.TEXT,
  web: DataTypes.STRING(80),
  fax: DataTypes.TEXT,
  email_perusahaan: DataTypes.STRING(80),
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'iklan' });

models.IklanFinish = sequelize.define('iklan_finish', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  owner: DataTypes.STRING(255),
  foto_owner: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  alamat_perusahaan: DataTypes.TEXT,
  phone: DataTypes.STRING(80),
  catatan: DataTypes.TEXT,
  phone_mobile: DataTypes.STRING(80),
  nama_perusahaan: DataTypes.TEXT,
  web: DataTypes.STRING(80),
  fax: DataTypes.TEXT,
  email_perusahaan: DataTypes.STRING(80),
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'iklan_finish' });

models.IklanPublish = sequelize.define('iklan_publish', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  owner: DataTypes.STRING(255),
  foto_owner: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  alamat_perusahaan: DataTypes.TEXT,
  phone: DataTypes.STRING(80),
  catatan: DataTypes.TEXT,
  phone_mobile: DataTypes.STRING(80),
  nama_perusahaan: DataTypes.TEXT,
  web: DataTypes.STRING(80),
  fax: DataTypes.TEXT,
  email_perusahaan: DataTypes.STRING(80),
  kategori: DataTypes.STRING(50),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'iklan_publish' });

models.Informasi = sequelize.define('informasi', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  informasi_views: DataTypes.INTEGER,
  informasi_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  informasi_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'informasi' });

models.Market = sequelize.define('market', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  market_views: DataTypes.INTEGER,
  market_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  deskripsi: DataTypes.TEXT,
  handphone: DataTypes.TEXT,
  harga: DataTypes.TEXT,
  market_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(1000),
}, { timestamps: false, tableName: 'market' });

models.Mymusic = sequelize.define('mymusic', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ...articleBaseFields,
  video: DataTypes.TEXT,
  video_title: DataTypes.TEXT,
  video_deskripsi: DataTypes.TEXT,
  audio: DataTypes.STRING(1000),
  audio_title: DataTypes.STRING(1000),
  audio_deskripsi: DataTypes.STRING(1000),
  pencipta: DataTypes.TEXT,
  produksi: DataTypes.STRING(80),
  penyanyi: DataTypes.TEXT,
  cover: DataTypes.STRING(480),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  posting_views: DataTypes.INTEGER,
  posting_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  posting_semester: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'mymusic' });

models.Mypdf = sequelize.define('mypdf', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ...articleBaseFields,
  video: DataTypes.TEXT,
  video_title: DataTypes.TEXT,
  video_deskripsi: DataTypes.TEXT,
  pdf: DataTypes.STRING(1000),
  pdf_title: DataTypes.STRING(1000),
  pdf_deskripsi: DataTypes.STRING(1000),
  pencipta: DataTypes.TEXT,
  produksi: DataTypes.STRING(80),
  penulis: DataTypes.TEXT,
  cover: DataTypes.STRING(480),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  posting_views: DataTypes.INTEGER,
  posting_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  posting_semester: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'mypdf' });

models.PesanTamu = sequelize.define('pesan_tamu', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ...articleBaseFields,
  sumber_gambar1: DataTypes.STRING(250),
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  ...textFields(30),
  pesan_tamu_views: DataTypes.INTEGER,
  pesan_tamu_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  pesan_tamu_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'pesan_tamu' });

module.exports = models;
