const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const models = {};

models.Ektp = sequelize.define('ektp', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  nik: DataTypes.STRING(16),
  nama_lengkap: DataTypes.STRING(25),
  jenis_kelamin: DataTypes.STRING(15),
  tanggal_lahir: DataTypes.STRING(10),
  tempat_lahir: DataTypes.STRING(20),
  agama: DataTypes.STRING(55),
  gol_darah: DataTypes.STRING(2),
  pekerjaan: DataTypes.STRING(25),
  status_kawin: DataTypes.STRING(100),
  alamat: DataTypes.STRING(25),
  rt: DataTypes.STRING(10),
  rw: DataTypes.STRING(10),
  kelurahan: DataTypes.STRING(20),
  kecamatan: DataTypes.STRING(20),
  kabupaten: DataTypes.STRING(20),
  provinsi: DataTypes.STRING(25),
  kk: DataTypes.STRING(10000),
  ponsel: DataTypes.STRING(15),
  image: DataTypes.STRING(100),
  surat_pengantar_rt: DataTypes.STRING(10000),
  surat_pengantar_rw: DataTypes.TEXT('medium'),
  Akta_Kelahiran: DataTypes.BLOB('long'),
  surat_ket_pindah: DataTypes.STRING(1250),
  Surat_Ket_Datang_Dari_Luarnegri: DataTypes.BLOB('long'),
  waktu_ktp: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'ektp' });

models.Events = sequelize.define('events', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.STRING(255),
  user_username: DataTypes.STRING(200),
  date: DataTypes.DATEONLY,
  created: DataTypes.DATE,
  modified: DataTypes.DATE,
  status: { type: DataTypes.TINYINT, defaultValue: 1 },
}, { timestamps: false, tableName: 'events' });

models.Follow = sequelize.define('follow', {
  follow_id: { type: DataTypes.INTEGER, primaryKey: true },
  follow_current_user: DataTypes.STRING(255),
  follow_current_user_id: DataTypes.TEXT,
  follow_profile_user: DataTypes.STRING(255),
  follow_profile_user_id: DataTypes.TEXT,
  follow_bisnis_user: DataTypes.STRING(200),
  follow_count: { type: DataTypes.INTEGER, defaultValue: 1 },
  foto_profile: DataTypes.TEXT,
  foto_follower: DataTypes.TEXT,
  follow_timestamp: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'follow' });

models.FollowBisnis = sequelize.define('follow_bisnis', {
  follow_id: { type: DataTypes.INTEGER, primaryKey: true },
  follow_current_user: DataTypes.STRING(255),
  follow_current_user_id: DataTypes.TEXT,
  follow_profile_user: DataTypes.STRING(255),
  follow_profile_user_id: DataTypes.TEXT,
  follow_bisnis_user: DataTypes.STRING(200),
  foto_profile: DataTypes.TEXT,
  foto_follower: DataTypes.TEXT,
  follow_timestamp: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'follow_bisnis' });

models.Forum1Topic = sequelize.define('forum1_topic', {
  forum1_topic_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  forum1_topic_kategori: DataTypes.STRING(20),
  forum1_topic_name: DataTypes.TEXT,
  forum1_topic_sumbergambar: DataTypes.STRING(200),
  forum1_topic_created_by: DataTypes.STRING(255),
  forum1_topic_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  forum1_topic_body: DataTypes.TEXT,
  forum1_topic_views: DataTypes.INTEGER,
  forum1_topic_replies: DataTypes.INTEGER,
  forum1_topic_semester: DataTypes.STRING(255),
  forum1_topic_image: DataTypes.STRING(255),
  image_asli: DataTypes.STRING(1000),
  image: DataTypes.STRING(1000),
  dataType: DataTypes.STRING(1000),
  title: DataTypes.STRING(1000),
  fileName: DataTypes.STRING(1000),
  video: DataTypes.STRING(1000),
}, { timestamps: false, tableName: 'forum1_topic' });

models.Forum1TopicReply = sequelize.define('forum1_topic_reply', {
  forum1_topic_reply_id: { type: DataTypes.INTEGER, primaryKey: true },
  forum1_topic_reply_topic_id: { type: DataTypes.INTEGER, primaryKey: true },
  forum1_topic_reply_created_by: DataTypes.STRING(255),
  forum1_topic_reply_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  forum1_topic_reply_body: DataTypes.TEXT,
  forum1_topic_reply_image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'forum1_topic_reply' });

models.Group = sequelize.define('group', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: { type: DataTypes.STRING(100), defaultValue: 'Slogan' },
  font_content: DataTypes.STRING(250),
  about_content: DataTypes.TEXT,
  home_content: DataTypes.TEXT,
  blog_content: DataTypes.TEXT,
  about_us: DataTypes.TEXT,
  what_we_do: DataTypes.TEXT,
  projects: DataTypes.TEXT,
  catatan: DataTypes.TEXT,
  shop: DataTypes.TEXT,
  features: DataTypes.TEXT,
  pricing: DataTypes.TEXT,
  services: DataTypes.TEXT,
  gallery_content: DataTypes.STRING(250),
  contact_content: DataTypes.STRING(250),
  email_content: DataTypes.STRING(550),
  adress_content: DataTypes.STRING(550),
  gps_content: DataTypes.STRING(250),
  url_web: DataTypes.STRING(50),
  web_kategori: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  image: DataTypes.TEXT,
  gallery_image: DataTypes.STRING(550),
  gallery_image1: DataTypes.STRING(550),
  gallery_image2: DataTypes.STRING(550),
  gallery_image3: DataTypes.STRING(550),
  gallery_image4: DataTypes.STRING(550),
  gallery_image5: DataTypes.STRING(550),
  gallery_image6: DataTypes.STRING(550),
  gallery_image7: DataTypes.STRING(550),
  gallery_image8: DataTypes.STRING(550),
  gallery_image9: DataTypes.STRING(550),
  audio: DataTypes.STRING(550),
  trend1: DataTypes.TEXT,
  trend2: DataTypes.TEXT,
  trend3: DataTypes.STRING(550),
  trend4: DataTypes.TEXT,
  trend5: DataTypes.STRING(550),
  trend6: DataTypes.TEXT,
  trend7: DataTypes.STRING(550),
  home: { type: DataTypes.STRING(25), defaultValue: 'home' },
  blog: { type: DataTypes.STRING(25), defaultValue: 'blog' },
  about: { type: DataTypes.STRING(25), defaultValue: 'about' },
  gallery: { type: DataTypes.STRING(25), defaultValue: 'gallery' },
  contact: { type: DataTypes.STRING(25), defaultValue: 'contact' },
  kode_referal: DataTypes.STRING(80),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  user_type_member: DataTypes.STRING(50),
  userstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  user_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  user_validasi: DataTypes.STRING(250),
  user_pesan_masuk: DataTypes.TEXT,
  user_pesan_keluar: DataTypes.TEXT,
  user_email: DataTypes.STRING(255),
  user_password: DataTypes.STRING(255),
  user_firstname: DataTypes.STRING(25),
  user_lastname: DataTypes.TEXT,
  user_ponsel: DataTypes.STRING(55),
  user_skill1: DataTypes.STRING(250),
  user_testimoni: DataTypes.STRING(250),
  user_skill2: DataTypes.STRING(250),
  user_typemember: DataTypes.STRING(255),
  user_avatar: { type: DataTypes.STRING(1000), defaultValue: 'img/default.png' },
  kode_aktivasi: DataTypes.STRING(10),
  user_shortbio: DataTypes.STRING(250),
  nama_pemilik: DataTypes.STRING(25),
  user_username: DataTypes.STRING(100),
  array_teman: DataTypes.STRING(550),
  user_longbio: DataTypes.STRING(300),
  user_facebook: DataTypes.STRING(255),
  user_twitter: DataTypes.STRING(255),
  user_linkedin: DataTypes.STRING(255),
  user_instagram: DataTypes.STRING(255),
  user_github: DataTypes.STRING(255),
  user_gietimes: DataTypes.STRING(255),
  user_onlineshoop: DataTypes.STRING(255),
  user_website: DataTypes.STRING(255),
  user_dob: DataTypes.DATEONLY,
  user_profession: DataTypes.STRING(25),
  user_gender: DataTypes.STRING(10),
  user_maritialstatus: DataTypes.STRING(10),
  user_address: DataTypes.TEXT,
  user_backgroundpicture: DataTypes.STRING(255),
  user_header: { type: DataTypes.STRING(200), defaultValue: '#ffffff' },
  font_header: { type: DataTypes.STRING(200), defaultValue: '#2f2e32' },
  name_header: DataTypes.STRING(550),
  right_footer: DataTypes.STRING(550),
  left_footer: DataTypes.STRING(550),
  user_footer: DataTypes.STRING(550),
  font_footer: DataTypes.STRING(550),
  user_joindate: DataTypes.DATEONLY,
  user_country: DataTypes.STRING(255),
  user_skype: DataTypes.STRING(255),
  user_youtube: DataTypes.STRING(255),
  user_win_project: DataTypes.INTEGER,
  user_date: DataTypes.DATEONLY,
  time: DataTypes.DATEONLY,
}, { timestamps: false, tableName: 'group' });

models.GroupPosting = sequelize.define('group_posting', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  nama_toko: DataTypes.STRING(50),
  jumlah_stok_barang: DataTypes.STRING(1000),
  harga: DataTypes.STRING(100),
  sumber_gambar: DataTypes.STRING(150),
  video: DataTypes.TEXT,
  video_title: DataTypes.TEXT,
  video_deskripsi: DataTypes.TEXT,
  audio: DataTypes.STRING(1000),
  audio_title: DataTypes.STRING(1000),
  audio_deskripsi: DataTypes.STRING(1000),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  isi_artikel30: DataTypes.TEXT,
  group_posting_views: DataTypes.INTEGER,
  group_posting_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  group_posting_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'group_posting' });

models.Infographic = sequelize.define('infographic', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  total_penduduk: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  kepala_keluarga: DataTypes.TEXT,
  perempuan: DataTypes.STRING(1280),
  laki_laki: DataTypes.TEXT,
  maps: DataTypes.TEXT,
  sd: DataTypes.TEXT,
  smp: DataTypes.STRING(1280),
  sma: DataTypes.TEXT,
  pt: DataTypes.STRING(80),
  kelontong: DataTypes.STRING(1250),
  warungmakanan: DataTypes.STRING(250),
  umkm: DataTypes.STRING(250),
  tokobangunan: DataTypes.STRING(250),
  panjangjalandesa: DataTypes.STRING(250),
  jalananaspal: DataTypes.STRING(250),
  jalananbeton: DataTypes.STRING(250),
  jalanantanah: DataTypes.STRING(250),
  jalananrusak: DataTypes.STRING(250),
  kebun1: DataTypes.STRING(250),
  kebun2: DataTypes.STRING(250),
  kebun3: DataTypes.STRING(250),
  kebun4: DataTypes.STRING(250),
  kebun5: DataTypes.STRING(250),
  islam: DataTypes.STRING(250),
  kristenprotestan: DataTypes.STRING(250),
  kristenkatolik: DataTypes.STRING(250),
  hindu: DataTypes.STRING(250),
  budha: DataTypes.TEXT,
  konghucu: DataTypes.STRING(1280),
  kepercayaan: DataTypes.TEXT,
  jumlahpemilih: DataTypes.STRING(1280),
  pemilihlaki_laki: DataTypes.TEXT,
  pemilihperempuan: DataTypes.STRING(1280),
  infographic34: DataTypes.TEXT,
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  infographic: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  admin_username: DataTypes.INTEGER,
}, { timestamps: false, tableName: 'infographic' });

models.KanalSave = sequelize.define('kanal_save', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  isi_artikel30: DataTypes.TEXT,
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  save_by: DataTypes.STRING(100),
}, { timestamps: false, tableName: 'kanal_save' });

module.exports = models;
