const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const models = {};

models.About = sequelize.define('about', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  name: DataTypes.TEXT,
  name_lengkap: DataTypes.STRING(50),
  status: DataTypes.STRING(50),
  kronologi: DataTypes.STRING(400),
  sumber_tulisan: DataTypes.STRING(150),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  body: DataTypes.TEXT,
  category: DataTypes.STRING(50),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'about' });

models.Apbdesa = sequelize.define('apbdesa', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  total_pendapatan: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  dana_desa: DataTypes.TEXT,
  alokasidana_1: DataTypes.STRING(1280),
  alokasidana_2: DataTypes.TEXT,
  maps: DataTypes.TEXT,
  sd: DataTypes.TEXT,
  smp: DataTypes.STRING(1280),
  sma: DataTypes.TEXT,
  pt: DataTypes.STRING(80),
  kelontong: DataTypes.STRING(1250),
  warungmakanan: DataTypes.STRING(250),
  umkm: DataTypes.STRING(250),
  tokobangunan: DataTypes.STRING(250),
  panjangjalandesa: DataTypes.STRING(250),
  jalananaspal: DataTypes.STRING(250),
  jalananbeton: DataTypes.STRING(250),
  jalanantanah: DataTypes.STRING(250),
  jalananrusak: DataTypes.STRING(250),
  kebun1: DataTypes.STRING(250),
  kebun2: DataTypes.STRING(250),
  kebun3: DataTypes.STRING(250),
  kebun4: DataTypes.STRING(250),
  kebun5: DataTypes.STRING(250),
  islam: DataTypes.STRING(250),
  kristenprotestan: DataTypes.STRING(250),
  kristenkatolik: DataTypes.STRING(250),
  hindu: DataTypes.STRING(250),
  budha: DataTypes.TEXT,
  konghucu: DataTypes.STRING(1280),
  kepercayaan: DataTypes.TEXT,
  jumlahpemilih: DataTypes.STRING(1280),
  pemilihlaki_laki: DataTypes.TEXT,
  pemilihperempuan: DataTypes.STRING(1280),
  apbdesa34: DataTypes.TEXT,
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  apbdesa: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  admin_username: { type: DataTypes.INTEGER, primaryKey: true },
}, { timestamps: false, tableName: 'apbdesa' });

models.Areas = sequelize.define('areas', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  name: DataTypes.STRING(255),
  geolocations: DataTypes.TEXT,
  keywords: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'areas' });

models.AsStatistics = sequelize.define('as_statistics', {
  ip: DataTypes.STRING(20),
  tanggal: DataTypes.DATEONLY,
  hits: DataTypes.INTEGER,
  online: { type: DataTypes.INTEGER, primaryKey: true },
}, { timestamps: false, tableName: 'as_statistics' });

models.Bisnis = sequelize.define('bisnis', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: { type: DataTypes.STRING(100), defaultValue: 'Slogan' },
  font_content: DataTypes.STRING(250),
  about_content: DataTypes.TEXT,
  home_content: DataTypes.TEXT,
  blog_content: DataTypes.TEXT,
  about_us: DataTypes.TEXT,
  what_we_do: DataTypes.TEXT,
  projects: DataTypes.TEXT,
  catatan: DataTypes.TEXT,
  shop: DataTypes.TEXT,
  features: DataTypes.TEXT,
  pricing: DataTypes.TEXT,
  services: DataTypes.TEXT,
  gallery_content: DataTypes.STRING(250),
  contact_content: DataTypes.STRING(250),
  email_content: DataTypes.STRING(550),
  adress_content: DataTypes.STRING(550),
  gps_content: DataTypes.STRING(250),
  url_web: DataTypes.STRING(50),
  web_kategori: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  image: DataTypes.TEXT,
  gallery_image: DataTypes.STRING(550),
  gallery_image1: DataTypes.STRING(550),
  gallery_image2: DataTypes.STRING(550),
  gallery_image3: DataTypes.STRING(550),
  gallery_image4: DataTypes.STRING(550),
  gallery_image5: DataTypes.STRING(550),
  gallery_image6: DataTypes.STRING(550),
  gallery_image7: DataTypes.STRING(550),
  gallery_image8: DataTypes.STRING(550),
  gallery_image9: DataTypes.STRING(550),
  audio: DataTypes.STRING(550),
  trend1: DataTypes.TEXT,
  trend2: DataTypes.TEXT,
  trend3: DataTypes.STRING(550),
  trend4: DataTypes.TEXT,
  trend5: DataTypes.STRING(550),
  trend6: DataTypes.TEXT,
  trend7: DataTypes.STRING(550),
  home: { type: DataTypes.STRING(25), defaultValue: 'home' },
  blog: { type: DataTypes.STRING(25), defaultValue: 'blog' },
  about: { type: DataTypes.STRING(25), defaultValue: 'about' },
  gallery: { type: DataTypes.STRING(25), defaultValue: 'gallery' },
  contact: { type: DataTypes.STRING(25), defaultValue: 'contact' },
  kode_referal: DataTypes.STRING(80),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  user_type_member: DataTypes.STRING(50),
  userstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  user_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  user_validasi: DataTypes.STRING(250),
  user_pesan_masuk: DataTypes.TEXT,
  user_pesan_keluar: DataTypes.TEXT,
  user_email: DataTypes.STRING(255),
  user_password: DataTypes.STRING(255),
  user_firstname: DataTypes.STRING(25),
  user_lastname: DataTypes.TEXT,
  user_ponsel: DataTypes.STRING(55),
  user_skill1: DataTypes.STRING(250),
  user_testimoni: DataTypes.STRING(250),
  user_skill2: DataTypes.STRING(250),
  user_typemember: DataTypes.STRING(255),
  user_avatar: { type: DataTypes.STRING(1000), defaultValue: 'img/default.png' },
  kode_aktivasi: DataTypes.STRING(10),
  user_shortbio: DataTypes.STRING(250),
  nama_pemilik: DataTypes.STRING(25),
  user_username: DataTypes.STRING(100),
  array_teman: DataTypes.STRING(550),
  user_longbio: DataTypes.STRING(300),
  user_facebook: DataTypes.STRING(255),
  user_twitter: DataTypes.STRING(255),
  user_linkedin: DataTypes.STRING(255),
  user_instagram: DataTypes.STRING(255),
  user_github: DataTypes.STRING(255),
  user_gietimes: DataTypes.STRING(255),
  user_onlineshoop: DataTypes.STRING(255),
  user_website: DataTypes.STRING(255),
  user_dob: DataTypes.DATEONLY,
  user_profession: DataTypes.STRING(25),
  user_gender: DataTypes.STRING(10),
  user_maritialstatus: DataTypes.STRING(10),
  user_address: DataTypes.TEXT,
  user_backgroundpicture: DataTypes.STRING(255),
  user_header: { type: DataTypes.STRING(200), defaultValue: '#ffffff' },
  font_header: { type: DataTypes.STRING(200), defaultValue: '#2f2e32' },
  name_header: DataTypes.STRING(550),
  right_footer: DataTypes.STRING(550),
  left_footer: DataTypes.STRING(550),
  user_footer: DataTypes.STRING(550),
  font_footer: DataTypes.STRING(550),
  user_joindate: DataTypes.DATEONLY,
  user_country: DataTypes.STRING(255),
  user_skype: DataTypes.STRING(255),
  user_youtube: DataTypes.STRING(255),
  user_win_project: DataTypes.INTEGER,
  user_date: DataTypes.DATEONLY,
  time: DataTypes.DATEONLY,
}, { timestamps: false, tableName: 'bisnis' });

models.ChatTopic = sequelize.define('chat_topic', {
  chat_topic_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  chat_topic_kategori: DataTypes.STRING(20),
  chat_topic_name: DataTypes.TEXT,
  chat_topic_sumbergambar: DataTypes.STRING(200),
  chat_topic_created_by: DataTypes.STRING(255),
  chat_topic_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  chat_topic_body: DataTypes.TEXT,
  chat_topic_views: DataTypes.INTEGER,
  chat_topic_replies: DataTypes.INTEGER,
  chat_topic_semester: DataTypes.STRING(255),
  chat_topic_image: DataTypes.STRING(255),
  image_asli: DataTypes.STRING(1000),
  image: DataTypes.STRING(1000),
  dataType: DataTypes.STRING(1000),
  title: DataTypes.STRING(1000),
  fileName: DataTypes.STRING(1000),
  video: DataTypes.STRING(1000),
}, { timestamps: false, tableName: 'chat_topic' });

models.ChatTopicReply = sequelize.define('chat_topic_reply', {
  chat_topic_reply_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  chat_topic_reply_topic_id: { type: DataTypes.INTEGER, primaryKey: true },
  chat_topic_reply_created_by: DataTypes.STRING(255),
  chat_topic_reply_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  chat_topic_reply_body: DataTypes.TEXT,
  chat_topic_reply_image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'chat_topic_reply' });

models.Companies = sequelize.define('companies', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  company: DataTypes.STRING(255),
  details: DataTypes.TEXT,
  latitude: DataTypes.STRING(255),
  longitude: DataTypes.STRING(255),
  telephone: DataTypes.STRING(255),
  keywords: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'companies' });

models.Contact = sequelize.define('contact', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  nama: DataTypes.STRING(50),
  alamat: DataTypes.TEXT,
  pekerjaan: DataTypes.STRING(50),
  telpon: DataTypes.STRING(15),
  created_by: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'contact' });

models.ContactPerusahaan = sequelize.define('contact_perusahaan', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  nama: DataTypes.STRING(50),
  alamat: DataTypes.TEXT,
  pekerjaan: DataTypes.STRING(50),
  telpon: DataTypes.STRING(15),
  created_by: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'contact_perusahaan' });

models.Counterdb = sequelize.define('counterdb', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  tanggal: DataTypes.DATEONLY,
  ip_address: DataTypes.STRING(20),
  counter: DataTypes.STRING(20),
  browser: DataTypes.STRING(20),
}, { timestamps: false, tableName: 'counterdb' });

models.Daftarkata = sequelize.define('daftarkata', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  indonesia: DataTypes.TEXT,
  inggris: DataTypes.TEXT,
}, { timestamps: false, tableName: 'daftarkata' });

models.Dagang = sequelize.define('dagang', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  nama_toko: DataTypes.STRING(50),
  jumlah_stok_barang: DataTypes.STRING(1000),
  harga: DataTypes.STRING(100),
  sumber_gambar: DataTypes.STRING(150),
  video: DataTypes.TEXT,
  video_title: DataTypes.TEXT,
  video_deskripsi: DataTypes.TEXT,
  audio: DataTypes.STRING(1000),
  audio_title: DataTypes.STRING(1000),
  audio_deskripsi: DataTypes.STRING(1000),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  isi_artikel30: DataTypes.TEXT,
  dagang_views: DataTypes.INTEGER,
  dagang_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  dagang_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'dagang' });

models.DagangTopicReply = sequelize.define('dagang_topic_reply', {
  dagang_topic_reply_id: { type: DataTypes.INTEGER, primaryKey: true },
  dagang_topic_reply_topic_id: { type: DataTypes.INTEGER, primaryKey: true },
  dagang_topic_reply_created_by: DataTypes.STRING(255),
  dagang_topic_reply_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  dagang_topic_reply_body: DataTypes.TEXT,
  nama_penulis: DataTypes.STRING(550),
  foto_penulis: DataTypes.TEXT,
  add_image: DataTypes.TEXT,
  title: DataTypes.STRING(550),
  id: DataTypes.STRING(550),
  dagang_topic_reply_image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'dagang_topic_reply' });

models.Dpac = sequelize.define('dpac', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  propinsi: DataTypes.TEXT,
  ketua: DataTypes.STRING(150),
  hp_ketua: DataTypes.STRING(250),
  nik_ktp_ketua: DataTypes.STRING(250),
  sekretaris: DataTypes.STRING(250),
  hp_sekretaris: DataTypes.STRING(250),
  nik_ktp_sekretaris: DataTypes.STRING(250),
  bendahara: DataTypes.STRING(50),
  hp_bendahara: DataTypes.STRING(250),
  nik_ktp_bendahara: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'dpac' });

models.Dpc = sequelize.define('dpc', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  propinsi: DataTypes.TEXT,
  ketua: DataTypes.STRING(150),
  hp_ketua: DataTypes.STRING(250),
  nik_ktp_ketua: DataTypes.STRING(250),
  sekretaris: DataTypes.STRING(250),
  hp_sekretaris: DataTypes.STRING(250),
  nik_ktp_sekretaris: DataTypes.STRING(250),
  bendahara: DataTypes.STRING(50),
  hp_bendahara: DataTypes.STRING(250),
  nik_ktp_bendahara: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'dpc' });

models.Dpd = sequelize.define('dpd', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  propinsi: DataTypes.TEXT,
  ketua: DataTypes.STRING(150),
  hp_ketua: DataTypes.STRING(250),
  nik_ktp_ketua: DataTypes.STRING(250),
  sekretaris: DataTypes.STRING(250),
  hp_sekretaris: DataTypes.STRING(250),
  nik_ktp_sekretaris: DataTypes.STRING(250),
  bendahara: DataTypes.STRING(50),
  hp_bendahara: DataTypes.STRING(250),
  nik_ktp_bendahara: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'dpd' });

models.Dpw = sequelize.define('dpw', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  propinsi: DataTypes.TEXT,
  ketua: DataTypes.STRING(150),
  hp_ketua: DataTypes.STRING(250),
  nik_ktp_ketua: DataTypes.STRING(250),
  sekretaris: DataTypes.STRING(250),
  hp_sekretaris: DataTypes.STRING(250),
  nik_ktp_sekretaris: DataTypes.STRING(250),
  bendahara: DataTypes.STRING(50),
  hp_bendahara: DataTypes.STRING(250),
  nik_ktp_bendahara: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
}, { timestamps: false, tableName: 'dpw' });

module.exports = models;
