const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const models = {};

models.Kategori = sequelize.define('kategori', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  kategori1: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  kategori2: DataTypes.TEXT,
  kategori3: DataTypes.STRING(1280),
  kategori4: DataTypes.TEXT,
  kategori5: DataTypes.STRING(1280),
  kategori6: DataTypes.TEXT,
  kategori7: DataTypes.STRING(1280),
  kategori8: DataTypes.TEXT,
  kategori9: DataTypes.STRING(80),
  kategori10: DataTypes.STRING(250),
  kategori11: DataTypes.STRING(250),
  kategori12: DataTypes.STRING(250),
  kategori13: DataTypes.STRING(250),
  kategori14: DataTypes.STRING(250),
  kategori15: DataTypes.STRING(250),
  kategori16: DataTypes.STRING(250),
  kategori17: DataTypes.STRING(250),
  kategori18: DataTypes.STRING(250),
  kategori19: DataTypes.STRING(250),
  kategori20: DataTypes.STRING(250),
  kategori21: DataTypes.STRING(250),
  kategori22: DataTypes.STRING(250),
  kategori23: DataTypes.STRING(250),
  kategori24: DataTypes.STRING(250),
  kategori25: DataTypes.STRING(250),
  kategori26: DataTypes.STRING(250),
  kategori27: DataTypes.STRING(250),
  kategori28: DataTypes.TEXT,
  kategori29: DataTypes.STRING(1280),
  kategori30: DataTypes.TEXT,
  kategori31: DataTypes.STRING(1280),
  kategori32: DataTypes.TEXT,
  kategori33: DataTypes.STRING(1280),
  kategori34: DataTypes.TEXT,
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  admin_username: DataTypes.STRING(11),
}, { timestamps: false, tableName: 'kategori' });

models.KategoriPage = sequelize.define('kategori_page', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  kategori_page1: DataTypes.TEXT,
  kategori_page2: DataTypes.TEXT,
  kategori_page3: DataTypes.STRING(1280),
  kategori_page4: DataTypes.TEXT,
  kategori_page5: DataTypes.STRING(1280),
  kategori_page6: DataTypes.TEXT,
  kategori_page7: DataTypes.STRING(1280),
  kategori_page8: DataTypes.TEXT,
  kategori_page9: DataTypes.STRING(80),
  kategori_page10: DataTypes.STRING(250),
  kategori_page11: DataTypes.STRING(250),
  kategori_page12: DataTypes.STRING(250),
  kategori_page13: DataTypes.STRING(250),
  kategori_page14: DataTypes.STRING(250),
  kategori_page15: DataTypes.STRING(250),
  kategori_page16: DataTypes.STRING(250),
  kategori_page17: DataTypes.STRING(250),
  kategori_page18: DataTypes.STRING(250),
  kategori_page19: DataTypes.STRING(250),
  kategori_page20: DataTypes.STRING(250),
  kategori_page21: DataTypes.STRING(250),
  kategori_page22: DataTypes.STRING(250),
  kategori_page23: DataTypes.STRING(250),
  kategori_page24: DataTypes.STRING(250),
  kategori_page25: DataTypes.STRING(250),
  kategori_page26: DataTypes.STRING(250),
  kategori_page27: DataTypes.STRING(250),
  kategori_page28: DataTypes.TEXT,
  kategori_page29: DataTypes.STRING(1280),
  kategori_page30: DataTypes.TEXT,
  kategori_page31: DataTypes.STRING(1280),
  kategori_page32: DataTypes.TEXT,
  kategori_page33: DataTypes.STRING(1280),
  kategori_page34: DataTypes.TEXT,
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  kategori_page: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  admin_username: DataTypes.STRING(11),
}, { timestamps: false, tableName: 'kategori_page' });

models.KategoriZone = sequelize.define('kategori_zone', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  kategori_zone1: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  kategori_zone2: DataTypes.TEXT,
  kategori_zone3: DataTypes.STRING(1280),
  kategori_zone4: DataTypes.TEXT,
  kategori_zone5: DataTypes.STRING(1280),
  kategori_zone6: DataTypes.TEXT,
  kategori_zone7: DataTypes.STRING(1280),
  kategori_zone8: DataTypes.TEXT,
  kategori_zone9: DataTypes.STRING(80),
  kategori_zone10: DataTypes.STRING(250),
  kategori_zone11: DataTypes.STRING(250),
  kategori_zone12: DataTypes.STRING(250),
  kategori_zone13: DataTypes.STRING(250),
  kategori_zone14: DataTypes.STRING(250),
  kategori_zone15: DataTypes.STRING(250),
  kategori_zone16: DataTypes.STRING(250),
  kategori_zone17: DataTypes.STRING(250),
  kategori_zone18: DataTypes.STRING(250),
  kategori_zone19: DataTypes.STRING(250),
  kategori_zone20: DataTypes.STRING(250),
  kategori_zone21: DataTypes.STRING(250),
  kategori_zone22: DataTypes.STRING(250),
  kategori_zone23: DataTypes.STRING(250),
  kategori_zone24: DataTypes.STRING(250),
  kategori_zone25: DataTypes.STRING(250),
  kategori_zone26: DataTypes.STRING(250),
  kategori_zone27: DataTypes.STRING(250),
  kategori_zone28: DataTypes.TEXT,
  kategori_zone29: DataTypes.STRING(1280),
  kategori_zone30: DataTypes.TEXT,
  kategori_zone31: DataTypes.STRING(1280),
  kategori_zone32: DataTypes.TEXT,
  kategori_zone33: DataTypes.STRING(1280),
  kategori_zone34: DataTypes.TEXT,
  iklan_views: DataTypes.STRING(11),
  iklan_replies: DataTypes.STRING(11),
  kategori_zone: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  admin_username: DataTypes.INTEGER(255),
}, { timestamps: false, tableName: 'kategori_zone' });

models.Login = sequelize.define('login', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  nama: DataTypes.STRING(150),
  alamat: DataTypes.STRING(250),
  hp: DataTypes.STRING(250),
  id_user: DataTypes.STRING(250),
  usia: DataTypes.STRING(250),
  email: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  login_views: DataTypes.INTEGER,
  login_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  login_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'login' });

models.Logout = sequelize.define('logout', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  nama: DataTypes.STRING(150),
  alamat: DataTypes.STRING(250),
  hp: DataTypes.STRING(250),
  id_user: DataTypes.STRING(250),
  usia: DataTypes.STRING(250),
  email: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  logout_views: DataTypes.INTEGER,
  logout_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  logout_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'logout' });

models.Magz = sequelize.define('magz', {
  magz_id: { type: DataTypes.INTEGER, primaryKey: true },
  magz_name: DataTypes.TEXT,
  magz_gender: DataTypes.STRING(50),
  magz_price: DataTypes.DECIMAL(10, 0),
  magz_jenis_bahan: { type: DataTypes.STRING(50), defaultValue: 'Tidak ada keterangan' },
  magz_ukuran: { type: DataTypes.STRING(50), defaultValue: 'tidak ada keterangan' },
  magz_warna: { type: DataTypes.STRING(50), defaultValue: 'tidak ada keterangan' },
  magz_status: DataTypes.STRING(50),
  magz_kronologi: DataTypes.STRING(400),
  magz_sumber_tulisan: DataTypes.STRING(150),
  magz_created_by: DataTypes.STRING(255),
  magz_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  magz_body: DataTypes.TEXT,
  magz_views: DataTypes.INTEGER,
  magz_replies: DataTypes.INTEGER,
  magz_category: DataTypes.STRING(50),
  magz_semester: DataTypes.STRING(255),
  magz_image: DataTypes.STRING(255),
  magz_image1: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'magz' });

models.Notes = sequelize.define('notes', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  nama_toko: DataTypes.STRING(50),
  jumlah_stok_barang: DataTypes.STRING(1000),
  harga: DataTypes.STRING(100),
  sumber_gambar: DataTypes.STRING(150),
  video: DataTypes.TEXT,
  video_title: DataTypes.TEXT,
  video_deskripsi: DataTypes.TEXT,
  audio: DataTypes.STRING(1000),
  audio_title: DataTypes.STRING(1000),
  audio_deskripsi: DataTypes.STRING(1000),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  isi_artikel30: DataTypes.TEXT,
  notes_views: DataTypes.INTEGER,
  notes_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  notes_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'notes' });

models.Pageview = sequelize.define('pageview', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  page: DataTypes.TEXT,
  userip: DataTypes.TEXT,
}, { timestamps: false, tableName: 'pageview' });

models.PaymentPending = sequelize.define('payment_pending', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  poin_artikel: { type: DataTypes.INTEGER, defaultValue: 10 },
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'payment_pending' });

models.PaymentRelease = sequelize.define('payment_release', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  nama_bank: DataTypes.STRING(250),
  nomer_rekening: DataTypes.STRING(50),
  pemilik_rekening: DataTypes.STRING(50),
  jumlah_transfer: DataTypes.STRING(50),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  isi_artikel1: DataTypes.TEXT,
  isi_artikel2: DataTypes.TEXT,
  isi_artikel3: DataTypes.TEXT,
  isi_artikel4: DataTypes.TEXT,
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  poin_artikel: { type: DataTypes.INTEGER, defaultValue: 10 },
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'payment_release' });

models.PaymentRequest = sequelize.define('payment_request', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  nama_bank: DataTypes.STRING(250),
  nomer_rekening: DataTypes.STRING(50),
  pemilik_rekening: DataTypes.STRING(50),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  poin_artikel: DataTypes.STRING(100),
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'payment_request' });

models.PendingPublish = sequelize.define('pending_publish', {
  id: { type: DataTypes.INTEGER, primaryKey: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  isi_artikel30: DataTypes.TEXT,
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.TEXT,
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'pending_publish' });

models.Publish = sequelize.define('publish', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  isi_artikel30: DataTypes.TEXT,
  poin: DataTypes.TEXT,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.TEXT,
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'publish' });

models.PublishGirl = sequelize.define('publish_girl', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'publish_girl' });

models.PublishMan = sequelize.define('publish_man', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'publish_man' });

models.PublishTop = sequelize.define('publish_top', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'publish_top' });

models.PublishTopicReply = sequelize.define('publish_topic_reply', {
  publish_topic_reply_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  publish_topic_reply_topic_id: { type: DataTypes.INTEGER, primaryKey: true },
  publish_topic_reply_created_by: DataTypes.STRING(255),
  publish_topic_reply_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  publish_topic_reply_body: DataTypes.TEXT,
  nama_penulis: DataTypes.STRING(550),
  foto_penulis: DataTypes.TEXT,
  add_image: DataTypes.TEXT,
  title: DataTypes.STRING(550),
  nik_ktp: DataTypes.STRING(550),
  sosial_media: DataTypes.STRING(550),
  user_address: DataTypes.STRING(550),
  user_ponsel: DataTypes.STRING(550),
  user_email: DataTypes.STRING(550),
  user_gender: DataTypes.STRING(550),
  user_age: DataTypes.STRING(550),
  id: DataTypes.STRING(550),
  publish_topic_reply_image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'publish_topic_reply' });

models.Storyblog = sequelize.define('storyblog', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.TEXT,
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT('long'),
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  poin: DataTypes.TEXT,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'storyblog' });

models.Trendkey = sequelize.define('trendkey', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  trend1: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  trend2: DataTypes.TEXT,
  trend3: DataTypes.STRING(80),
  trend4: DataTypes.TEXT,
  trend5: DataTypes.STRING(80),
  trend6: DataTypes.TEXT,
  trend7: DataTypes.STRING(80),
  trend8: DataTypes.TEXT,
  trend9: DataTypes.STRING(80),
  trend10: DataTypes.STRING(250),
  trend11: DataTypes.STRING(250),
  trend12: DataTypes.STRING(250),
  trend13: DataTypes.STRING(250),
  trend14: DataTypes.STRING(250),
  trend15: DataTypes.STRING(250),
  trend16: DataTypes.STRING(250),
  trend17: DataTypes.STRING(250),
  trend18: DataTypes.STRING(250),
  trend19: DataTypes.STRING(250),
  trend20: DataTypes.STRING(250),
  trend21: DataTypes.STRING(250),
  trend22: DataTypes.STRING(250),
  trend23: DataTypes.STRING(250),
  trend24: DataTypes.STRING(250),
  trend25: DataTypes.STRING(250),
  trend26: DataTypes.STRING(250),
  trend27: DataTypes.STRING(250),
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'trendkey' });

models.Tube = sequelize.define('tube', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  tube1: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  tube2: DataTypes.TEXT,
  tube3: DataTypes.STRING(1280),
  tube4: DataTypes.TEXT,
  tube5: DataTypes.STRING(1280),
  tube6: DataTypes.TEXT,
  tube7: DataTypes.STRING(1280),
  tube8: DataTypes.TEXT,
  tube9: DataTypes.STRING(80),
  tube10: DataTypes.STRING(250),
  tube11: DataTypes.STRING(250),
  tube12: DataTypes.STRING(250),
  tube13: DataTypes.STRING(250),
  tube14: DataTypes.STRING(250),
  tube15: DataTypes.STRING(250),
  tube16: DataTypes.STRING(250),
  tube17: DataTypes.STRING(250),
  tube18: DataTypes.STRING(250),
  tube19: DataTypes.STRING(250),
  tube20: DataTypes.STRING(250),
  tube21: DataTypes.STRING(250),
  tube22: DataTypes.STRING(250),
  tube23: DataTypes.STRING(250),
  tube24: DataTypes.STRING(250),
  tube25: DataTypes.STRING(250),
  tube26: DataTypes.STRING(250),
  tube27: DataTypes.STRING(250),
  tube28: DataTypes.TEXT,
  tube29: DataTypes.STRING(1280),
  tube30: DataTypes.TEXT,
  tube31: DataTypes.STRING(1280),
  tube32: DataTypes.TEXT,
  tube33: DataTypes.STRING(1280),
  tube34: DataTypes.TEXT,
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  tube: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
  admin_username: DataTypes.INTEGER,
}, { timestamps: false, tableName: 'tube' });

models.UserTop = sequelize.define('user_top', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  nama_bank: DataTypes.STRING(250),
  nomer_rekening: DataTypes.STRING(50),
  pemilik_rekening: DataTypes.STRING(50),
  jumlah_transfer: DataTypes.STRING(50),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  isi_artikel1: DataTypes.TEXT,
  isi_artikel2: DataTypes.TEXT,
  isi_artikel3: DataTypes.TEXT,
  isi_artikel4: DataTypes.TEXT,
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  poin_artikel: { type: DataTypes.INTEGER, defaultValue: 10 },
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'user_top' });

models.VideoBerdiri = sequelize.define('video_berdiri', {
  video_berdiri_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  video_berdiri_budget: DataTypes.STRING(50),
  video_berdiri_location: DataTypes.STRING(50),
  video_berdiri_time_end: DataTypes.STRING(50),
  video_berdiri_name: DataTypes.TEXT,
  video_berdiri_created_by: DataTypes.STRING(255),
  video_berdiri_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  video_berdiri_sumber: DataTypes.STRING(50),
  video_berdiri_transaction: DataTypes.STRING(50),
  video_berdiri_body: DataTypes.STRING(500),
  video_berdiri_views: DataTypes.INTEGER,
  video_berdiri_replies: DataTypes.INTEGER,
  video_berdiri_category: DataTypes.STRING(50),
  video_berdiri_semester: DataTypes.STRING(255),
  video_berdiri_foto: DataTypes.STRING(1000),
  video_berdiri_image: DataTypes.STRING(255),
  video_berdiri_video: DataTypes.STRING(2255),
}, { timestamps: false, tableName: 'video_berdiri' });

models.VideoTopic = sequelize.define('video_topic', {
  video_topic_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  video_topic_budget: DataTypes.STRING(50),
  video_topic_location: DataTypes.STRING(50),
  video_topic_time_end: DataTypes.STRING(50),
  video_topic_name: DataTypes.TEXT,
  video_topic_created_by: DataTypes.STRING(255),
  video_topic_time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  video_topic_sumber: DataTypes.STRING(50),
  video_topic_body: DataTypes.STRING(5000),
  video_topic_category: DataTypes.STRING(50),
  video_topic_image: DataTypes.STRING(255),
  video_topic_video: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'video_topic' });

models.Webinfo = sequelize.define('webinfo', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  trend1: DataTypes.TEXT,
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  trend2: DataTypes.TEXT,
  trend3: DataTypes.STRING(1280),
  trend4: DataTypes.TEXT,
  trend5: DataTypes.STRING(1280),
  trend6: DataTypes.TEXT,
  trend7: DataTypes.STRING(1280),
  trend8: DataTypes.TEXT,
  trend9: DataTypes.STRING(80),
  trend10: DataTypes.STRING(250),
  trend11: DataTypes.STRING(250),
  trend12: DataTypes.STRING(250),
  trend13: DataTypes.STRING(250),
  trend14: DataTypes.STRING(250),
  trend15: DataTypes.STRING(250),
  trend16: DataTypes.STRING(250),
  trend17: DataTypes.STRING(250),
  trend18: DataTypes.STRING(250),
  trend19: DataTypes.STRING(250),
  trend20: DataTypes.STRING(250),
  trend21: DataTypes.STRING(250),
  trend22: DataTypes.STRING(250),
  trend23: DataTypes.STRING(250),
  trend24: DataTypes.STRING(250),
  trend25: DataTypes.STRING(250),
  trend26: DataTypes.STRING(250),
  trend27: DataTypes.STRING(250),
  iklan_views: DataTypes.INTEGER,
  iklan_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  iklan_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'webinfo' });

models.Website = sequelize.define('website', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(80),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(80),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(80),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(80),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(80),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  link_website: DataTypes.TEXT,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.STRING(50),
  upfrom: DataTypes.STRING(50),
  deskripsi: DataTypes.TEXT,
  handphone: DataTypes.TEXT,
  harga: DataTypes.TEXT,
  image: DataTypes.STRING(255),
  image1: DataTypes.STRING(255),
  image2: DataTypes.STRING(250),
  image3: DataTypes.STRING(250),
  image4: DataTypes.STRING(250),
  image5: DataTypes.STRING(250),
}, { timestamps: false, tableName: 'website' });

models.WebPublish = sequelize.define('web_publish', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  title: DataTypes.TEXT,
  sumber_gambar: DataTypes.STRING(150),
  sumber_gambar1: DataTypes.STRING(250),
  sumber_gambar2: DataTypes.STRING(250),
  sumber_gambar3: DataTypes.STRING(250),
  sumber_gambar4: DataTypes.STRING(250),
  sumber_gambar5: DataTypes.STRING(250),
  nama_penulis: DataTypes.STRING(50),
  id_penulis: DataTypes.STRING(250),
  foto_penulis: DataTypes.STRING(250),
  created_by: DataTypes.STRING(255),
  add_image: DataTypes.STRING(250),
  add_image1: DataTypes.STRING(250),
  add_image2: DataTypes.STRING(250),
  add_image3: DataTypes.STRING(250),
  add_image4: DataTypes.STRING(250),
  add_image5: DataTypes.STRING(250),
  artikel_id: DataTypes.STRING(250),
  time: { type: DataTypes.DATE, defaultValue: DataTypes.NOW },
  isi_artikel: DataTypes.TEXT,
  sub_title1: DataTypes.STRING(100),
  isi_artikel1: DataTypes.TEXT,
  sub_title2: DataTypes.STRING(100),
  isi_artikel2: DataTypes.TEXT,
  sub_title3: DataTypes.STRING(100),
  isi_artikel3: DataTypes.TEXT,
  sub_title4: DataTypes.STRING(100),
  isi_artikel4: DataTypes.TEXT,
  sub_title5: DataTypes.STRING(100),
  isi_artikel5: DataTypes.TEXT,
  isi_artikel6: DataTypes.TEXT,
  isi_artikel7: DataTypes.TEXT,
  isi_artikel8: DataTypes.TEXT,
  isi_artikel9: DataTypes.TEXT,
  isi_artikel10: DataTypes.TEXT,
  isi_artikel11: DataTypes.TEXT,
  isi_artikel12: DataTypes.TEXT,
  isi_artikel13: DataTypes.TEXT,
  isi_artikel14: DataTypes.TEXT,
  isi_artikel15: DataTypes.TEXT,
  isi_artikel16: DataTypes.TEXT,
  isi_artikel17: DataTypes.TEXT,
  isi_artikel18: DataTypes.TEXT,
  isi_artikel19: DataTypes.TEXT,
  isi_artikel20: DataTypes.TEXT,
  isi_artikel21: DataTypes.TEXT,
  isi_artikel22: DataTypes.TEXT,
  isi_artikel23: DataTypes.TEXT,
  isi_artikel24: DataTypes.TEXT,
  isi_artikel25: DataTypes.TEXT,
  isi_artikel26: DataTypes.TEXT,
  isi_artikel27: DataTypes.TEXT,
  isi_artikel28: DataTypes.TEXT,
  isi_artikel29: DataTypes.TEXT,
  link_website: DataTypes.TEXT,
  story_views: DataTypes.INTEGER,
  story_replies: DataTypes.INTEGER,
  kategori: DataTypes.STRING(50),
  penulis_asli: DataTypes.STRING(50),
  judul_asli: DataTypes.STRING(100),
  jenis_artikel: DataTypes.STRING(50),
  id_asli: DataTypes.STRING(50),
  image_asli: DataTypes.TEXT,
  image_asli_penulis: DataTypes.TEXT,
  user_writer_category: DataTypes.TEXT,
  deskripsi: DataTypes.TEXT,
  handphone: DataTypes.TEXT,
  harga: DataTypes.TEXT,
  story_semester: DataTypes.STRING(255),
  image: DataTypes.STRING(255),
}, { timestamps: false, tableName: 'web_publish' });

module.exports = models;
