const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const userFields = {
  kode_referal: DataTypes.STRING(80),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  user_type_member: DataTypes.STRING(50),
  userstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  user_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  user_validasi: DataTypes.STRING(250),
  user_pesan_masuk: DataTypes.TEXT,
  user_pesan_keluar: DataTypes.TEXT,
  user_email: DataTypes.STRING(255),
  user_password: DataTypes.STRING(255),
  user_firstname: DataTypes.STRING(25),
  user_lastname: DataTypes.TEXT,
  user_ponsel: DataTypes.STRING(255),
  user_skill1: DataTypes.STRING(250),
  user_testimoni: DataTypes.STRING(250),
  user_skill2: DataTypes.STRING(250),
  user_typemember: DataTypes.STRING(255),
  user_level: DataTypes.STRING(20),
  user_upah_perproject: DataTypes.INTEGER(12),
  user_avatar: DataTypes.STRING(255),
  kode_aktivasi: DataTypes.STRING(10),
  user_shortbio: DataTypes.STRING(250),
  user_username: DataTypes.STRING(25),
  user_saldo: DataTypes.STRING(255),
  user_deposit: DataTypes.INTEGER,
  user_konfirmasi_bayar: DataTypes.STRING(250),
  user_produk_laku: DataTypes.STRING(255),
  user_point_reward: DataTypes.INTEGER,
  user_longbio: DataTypes.STRING(300),
  user_facebook: DataTypes.STRING(255),
  user_twitter: DataTypes.STRING(255),
  user_linkedin: DataTypes.STRING(255),
  user_stumbleupon: DataTypes.STRING(255),
  user_instagram: DataTypes.STRING(255),
  user_googleplus: DataTypes.STRING(255),
  user_website: DataTypes.STRING(255),
  user_dob: DataTypes.DATEONLY,
  user_profession: DataTypes.STRING(25),
  user_gender: DataTypes.STRING(255),
  user_maritialstatus: DataTypes.STRING(255),
  user_address: DataTypes.TEXT,
  user_backgroundpicture: DataTypes.STRING(255),
  user_joindate: DataTypes.DATEONLY,
  user_country: DataTypes.STRING(255),
  user_skype: DataTypes.STRING(255),
  user_github: DataTypes.STRING(255),
  user_youtube: DataTypes.STRING(255),
  user_vimeo: DataTypes.STRING(255),
  user_freelancer_category: DataTypes.STRING(250),
  user_gallery: DataTypes.STRING(255),
  user_gallery_category: DataTypes.STRING(20),
  user_company: DataTypes.STRING(25),
  user_writer_category: { type: DataTypes.STRING(25), defaultValue: 'New member community' },
  user_win_project: DataTypes.INTEGER,
  user_debit: DataTypes.INTEGER,
  user_selling: DataTypes.INTEGER,
  user_saldo_total: DataTypes.STRING(50),
  user_date: DataTypes.DATEONLY,
  user_invoice: DataTypes.INTEGER(255),
  user_yang_ingin_direkrut: DataTypes.STRING(50),
};

const models = {};

models.Admin = sequelize.define('admin', {
  admin_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  kode_referal: DataTypes.STRING(80),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  admin_type_member: DataTypes.STRING(50),
  adminstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  admin_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  admin_validasi: DataTypes.STRING(250),
  admin_pesan_masuk: DataTypes.TEXT,
  admin_pesan_keluar: DataTypes.TEXT,
  admin_email: { type: DataTypes.STRING(255), unique: true },
  admin_password: DataTypes.STRING(255),
  site_name: DataTypes.STRING(100),
  meta_title: DataTypes.TEXT,
  ponsel: DataTypes.STRING(255),
  keywords: DataTypes.STRING(1000),
  language: DataTypes.STRING(1000),
  founder: DataTypes.STRING(250),
  admin_typemember: DataTypes.STRING(255),
  admin_upah_perproject: DataTypes.INTEGER(12),
  admin_avatar: DataTypes.STRING(255),
  admin_backgroundpc: DataTypes.STRING(1000),
  deskripsi: DataTypes.STRING(1000),
  admin_username: { type: DataTypes.STRING(25), unique: true },
  admin_backgroundapp: DataTypes.STRING(1000),
  nama_sekdes: DataTypes.STRING(200),
  admin_konfirmasi_bayar: DataTypes.STRING(250),
  admin_aboutpicture: DataTypes.STRING(255),
  kecamatan: DataTypes.STRING(1000),
  admin_longbio: DataTypes.STRING(1000),
  facebook: DataTypes.STRING(255),
  twitter: DataTypes.STRING(255),
  admin_linkedin: DataTypes.STRING(255),
  admin_poin: DataTypes.STRING(255),
  instagram: DataTypes.STRING(255),
  admin_skillpicture: DataTypes.STRING(255),
  admin_website: DataTypes.STRING(255),
  admin_dob: DataTypes.DATEONLY,
  admin_profesi: DataTypes.STRING(125),
  kabupaten: DataTypes.STRING(1000),
  admin_maritialstatus: DataTypes.STRING(255),
  address: DataTypes.TEXT,
  admin_backgroundpicture: DataTypes.STRING(255),
  admin_joindate: DataTypes.DATEONLY,
  provinsi: DataTypes.STRING(255),
  url_web: DataTypes.STRING(255),
  logo_tengah: DataTypes.STRING(1255),
  youtube1: DataTypes.STRING(255),
  content: DataTypes.STRING(1000),
  admin_freelancer_category: DataTypes.STRING(250),
  admin_gallery: DataTypes.STRING(255),
  admin_gallery_category: DataTypes.STRING(20),
  admin_company: DataTypes.STRING(25),
  admin_1: { type: DataTypes.STRING(25), defaultValue: 'New member community' },
  admin_win_project: DataTypes.INTEGER,
  admin_debit: DataTypes.INTEGER,
  admin_selling: DataTypes.INTEGER,
  admin_saldo_total: DataTypes.STRING(50),
  admin_date: DataTypes.DATEONLY,
  admin_invoice: DataTypes.INTEGER(255),
  site_themes: DataTypes.STRING(50),
}, { timestamps: false, tableName: 'admin' });

models.AdminDepartemen = sequelize.define('admin_departemen', {
  admin_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  kode_referal: DataTypes.STRING(80),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  admin_type_member: DataTypes.STRING(50),
  adminstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  admin_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  admin_validasi: DataTypes.STRING(250),
  admin_pesan_masuk: DataTypes.TEXT,
  admin_pesan_keluar: DataTypes.TEXT,
  admin_email: { type: DataTypes.STRING(255), unique: true },
  admin_password: DataTypes.STRING(255),
  site_name: DataTypes.STRING(100),
  meta_title: DataTypes.TEXT,
  ponsel: DataTypes.STRING(255),
  keywords: DataTypes.STRING(1000),
  language: DataTypes.STRING(1000),
  founder: DataTypes.STRING(250),
  admin_typemember: DataTypes.STRING(255),
  admin_upah_perproject: DataTypes.INTEGER(12),
  admin_avatar: DataTypes.STRING(255),
  admin_backgroundpc: DataTypes.STRING(1000),
  deskripsi: DataTypes.STRING(1000),
  admin_username: { type: DataTypes.STRING(25), unique: true },
  admin_backgroundapp: DataTypes.STRING(1000),
  nama_sekdes: DataTypes.STRING(200),
  admin_konfirmasi_bayar: DataTypes.STRING(250),
  admin_aboutpicture: DataTypes.STRING(255),
  kecamatan: DataTypes.STRING(1000),
  admin_longbio: DataTypes.STRING(1000),
  facebook: DataTypes.STRING(255),
  twitter: DataTypes.STRING(255),
  admin_linkedin: DataTypes.STRING(255),
  admin_stumbleupon: DataTypes.STRING(255),
  instagram: DataTypes.STRING(255),
  admin_skillpicture: DataTypes.STRING(255),
  admin_website: DataTypes.STRING(255),
  admin_dob: DataTypes.DATEONLY,
  admin_profesi: DataTypes.STRING(125),
  kabupaten: DataTypes.STRING(1000),
  admin_maritialstatus: DataTypes.STRING(255),
  address: DataTypes.TEXT,
  admin_backgroundpicture: DataTypes.STRING(255),
  admin_joindate: DataTypes.DATEONLY,
  provinsi: DataTypes.STRING(255),
  url_web: DataTypes.STRING(255),
  logo_tengah: DataTypes.STRING(1255),
  youtube1: DataTypes.STRING(255),
  content: DataTypes.STRING(1000),
  admin_freelancer_category: DataTypes.STRING(250),
  admin_gallery: DataTypes.STRING(255),
  admin_gallery_category: DataTypes.STRING(20),
  admin_company: DataTypes.STRING(25),
  admin_1: { type: DataTypes.STRING(25), defaultValue: 'New member community' },
  admin_win_project: DataTypes.INTEGER,
  admin_debit: DataTypes.INTEGER,
  admin_selling: DataTypes.INTEGER,
  admin_saldo_total: DataTypes.STRING(50),
  admin_date: DataTypes.DATEONLY,
  admin_invoice: DataTypes.INTEGER(255),
  site_themes: DataTypes.STRING(50),
}, { timestamps: false, tableName: 'admin_departemen' });

models.AdminMagz = sequelize.define('admin_magz', {
  admin_id: { type: DataTypes.INTEGER, primaryKey: true },
  admin_type_member: DataTypes.STRING(50),
  userstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.CHAR(1),
  admin_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  admin_validasi: DataTypes.STRING(250),
  admin_pesan_masuk: DataTypes.TEXT,
  admin_pesan_keluar: DataTypes.TEXT,
  admin_email: DataTypes.STRING(255),
  admin_password: DataTypes.STRING(255),
  admin_firstname: DataTypes.STRING(25),
  admin_lastname: DataTypes.TEXT,
  admin_ponsel: DataTypes.STRING(255),
  admin_skill1: DataTypes.STRING(250),
  admin_testimoni: DataTypes.STRING(250),
  admin_skill2: DataTypes.STRING(250),
  admin_typemember: DataTypes.STRING(255),
  admin_level: DataTypes.STRING(20),
  admin_upah_perproject: DataTypes.INTEGER(12),
  admin_avatar: DataTypes.STRING(255),
  kode_aktivasi: DataTypes.STRING(10),
  admin_shortbio: DataTypes.STRING(250),
  admin_username: DataTypes.STRING(25),
  admin_saldo: DataTypes.STRING(255),
  admin_deposit: DataTypes.INTEGER,
  admin_konfirmasi_bayar: DataTypes.STRING(250),
  admin_produk_laku: DataTypes.STRING(255),
  admin_point_reward: DataTypes.INTEGER,
  admin_longbio: DataTypes.STRING(300),
  admin_facebook: DataTypes.STRING(255),
  admin_twitter: DataTypes.STRING(255),
  admin_linkedin: DataTypes.STRING(255),
  admin_stumbleupon: DataTypes.STRING(255),
  admin_instagram: DataTypes.STRING(255),
  admin_googleplus: DataTypes.STRING(255),
  admin_website: DataTypes.STRING(255),
  admin_dob: DataTypes.DATEONLY,
  admin_profession: DataTypes.STRING(25),
  admin_gender: DataTypes.STRING(255),
  admin_maritialstatus: DataTypes.STRING(255),
  admin_address: DataTypes.TEXT,
  admin_backgroundpicture: DataTypes.STRING(255),
  admin_joindate: DataTypes.DATEONLY,
  admin_country: DataTypes.STRING(255),
  admin_skype: DataTypes.STRING(255),
  admin_github: DataTypes.STRING(255),
  admin_youtube: DataTypes.STRING(255),
  admin_vimeo: DataTypes.STRING(255),
  admin_freelancer_category: DataTypes.STRING(250),
  admin_gallery: DataTypes.STRING(255),
  admin_gallery_category: DataTypes.STRING(20),
  admin_company: DataTypes.STRING(25),
  admin_company_category: DataTypes.STRING(25),
  admin_win_project: DataTypes.INTEGER,
  admin_debit: DataTypes.INTEGER,
  admin_selling: DataTypes.INTEGER,
  admin_saldo_total: DataTypes.INTEGER,
  admin_date: DataTypes.DATEONLY,
  admin_invoice: DataTypes.INTEGER(255),
  admin_yang_ingin_direkrut: DataTypes.STRING(50),
}, { timestamps: false, tableName: 'admin_magz' });

models.Admiral = sequelize.define('admiral', {
  user_id: { type: DataTypes.INTEGER, primaryKey: true },
  ...userFields,
  user_header: DataTypes.STRING(550),
  font_header: DataTypes.STRING(550),
  name_header: DataTypes.STRING(550),
  right_footer: DataTypes.STRING(550),
  left_footer: DataTypes.STRING(550),
  user_footer: DataTypes.STRING(550),
  font_footer: DataTypes.STRING(550),
}, { timestamps: false, tableName: 'admiral' });

models.User = sequelize.define('user', {
  user_id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  kode_referal: DataTypes.STRING(80),
  user_age: DataTypes.STRING(100),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  user_type_member: DataTypes.STRING(50),
  user_username: { type: DataTypes.STRING(25), unique: true },
  user_password: DataTypes.STRING(255),
  userstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.STRING(100),
  user_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  user_validasi: DataTypes.STRING(250),
  user_pesan_masuk: DataTypes.TEXT,
  user_pesan_keluar: DataTypes.TEXT,
  user_email: { type: DataTypes.STRING(255), unique: true },
  user_firstname: DataTypes.STRING(25),
  user_lastname: DataTypes.TEXT,
  user_ponsel: DataTypes.STRING(255),
  user_skill1: DataTypes.STRING(250),
  user_testimoni: DataTypes.STRING(250),
  user_skill2: DataTypes.STRING(250),
  user_typemember: DataTypes.STRING(255),
  user_level: DataTypes.STRING(20),
  user_upah_perproject: DataTypes.STRING(125),
  user_avatar: DataTypes.STRING(255),
  kode_aktivasi: DataTypes.STRING(10),
  user_shortbio: DataTypes.STRING(250),
  user_saldo: DataTypes.STRING(255),
  user_deposit: DataTypes.STRING(111),
  user_konfirmasi_bayar: DataTypes.STRING(250),
  user_produk_laku: DataTypes.STRING(255),
  user_point_reward: DataTypes.STRING(111),
  user_longbio: DataTypes.STRING(300),
  user_facebook: DataTypes.STRING(255),
  user_twitter: DataTypes.STRING(255),
  user_linkedin: DataTypes.STRING(255),
  sosial_media: DataTypes.STRING(255),
  user_instagram: DataTypes.STRING(255),
  nik_ktp: DataTypes.STRING(255),
  user_website: DataTypes.STRING(255),
  user_dob: DataTypes.STRING(255),
  user_profession: DataTypes.STRING(25),
  user_gender: DataTypes.STRING(255),
  user_maritialstatus: DataTypes.STRING(255),
  user_address: DataTypes.TEXT,
  user_backgroundpicture: DataTypes.STRING(255),
  user_header: DataTypes.STRING(550),
  font_header: DataTypes.STRING(550),
  name_header: DataTypes.STRING(550),
  right_footer: DataTypes.STRING(550),
  left_footer: DataTypes.STRING(550),
  user_footer: DataTypes.STRING(550),
  font_footer: DataTypes.STRING(550),
  user_joindate: DataTypes.DATEONLY,
  user_country: DataTypes.STRING(255),
  user_skype: DataTypes.STRING(255),
  user_github: DataTypes.STRING(255),
  user_youtube: DataTypes.STRING(255),
  user_vimeo: DataTypes.STRING(255),
  user_freelancer_category: DataTypes.STRING(250),
  user_gallery: DataTypes.STRING(255),
  user_gallery_category: DataTypes.STRING(20),
  user_company: DataTypes.STRING(25),
  user_writer_category: { type: DataTypes.STRING(25), defaultValue: 'New member community' },
  user_win_project: DataTypes.INTEGER,
  user_debit: DataTypes.INTEGER,
  user_selling: DataTypes.INTEGER,
  user_saldo_total: DataTypes.STRING(50),
  user_date: DataTypes.DATEONLY,
  user_invoice: DataTypes.INTEGER(255),
  user_yang_ingin_direkrut: DataTypes.STRING(50),
}, { timestamps: false, tableName: 'user' });

models.Hrd = sequelize.define('hrd', {
  user_id: { type: DataTypes.INTEGER, primaryKey: true },
  kode_referal: DataTypes.STRING(80),
  user_age: DataTypes.STRING(100),
  poin_referal: { type: DataTypes.INTEGER, defaultValue: 3 },
  user_type_member: DataTypes.STRING(50),
  userstatus: { type: DataTypes.STRING(50), defaultValue: 'None' },
  verificationCode: DataTypes.STRING(10),
  status: DataTypes.STRING(100),
  user_services: { type: DataTypes.STRING(1000), defaultValue: 'Information services none' },
  user_validasi: DataTypes.STRING(250),
  user_pesan_masuk: DataTypes.TEXT,
  user_pesan_keluar: DataTypes.TEXT,
  user_email: DataTypes.STRING(255),
  user_password: DataTypes.STRING(255),
  user_firstname: DataTypes.STRING(25),
  user_lastname: DataTypes.TEXT,
  user_ponsel: DataTypes.STRING(255),
  user_skill1: DataTypes.STRING(250),
  user_testimoni: DataTypes.STRING(250),
  user_skill2: DataTypes.STRING(250),
  user_typemember: DataTypes.STRING(255),
  user_level: DataTypes.STRING(20),
  user_upah_perproject: DataTypes.INTEGER(12),
  user_avatar: DataTypes.STRING(255),
  kode_aktivasi: DataTypes.STRING(10),
  user_shortbio: DataTypes.STRING(250),
  user_username: DataTypes.STRING(25),
  user_saldo: DataTypes.STRING(255),
  user_deposit: DataTypes.INTEGER,
  user_konfirmasi_bayar: DataTypes.STRING(250),
  user_produk_laku: DataTypes.STRING(255),
  user_point_reward: DataTypes.INTEGER,
  user_longbio: DataTypes.STRING(300),
  user_facebook: DataTypes.STRING(255),
  user_twitter: DataTypes.STRING(255),
  user_linkedin: DataTypes.STRING(255),
  user_stumbleupon: DataTypes.STRING(255),
  user_instagram: DataTypes.STRING(255),
  user_googleplus: DataTypes.STRING(255),
  user_website: DataTypes.STRING(255),
  user_dob: DataTypes.DATEONLY,
  user_profession: DataTypes.STRING(25),
  user_gender: DataTypes.STRING(255),
  user_maritialstatus: DataTypes.STRING(255),
  user_address: DataTypes.TEXT,
  user_backgroundpicture: DataTypes.STRING(255),
  user_header: DataTypes.STRING(550),
  font_header: DataTypes.STRING(550),
  name_header: DataTypes.STRING(550),
  right_footer: DataTypes.STRING(550),
  left_footer: DataTypes.STRING(550),
  user_footer: DataTypes.STRING(550),
  font_footer: DataTypes.STRING(550),
  user_joindate: DataTypes.DATEONLY,
  user_country: DataTypes.STRING(255),
  user_skype: DataTypes.STRING(255),
  user_github: DataTypes.STRING(255),
  user_youtube: DataTypes.STRING(255),
  user_vimeo: DataTypes.STRING(255),
  user_freelancer_category: DataTypes.STRING(250),
  user_gallery: DataTypes.STRING(255),
  user_gallery_category: DataTypes.STRING(20),
  user_company: DataTypes.STRING(25),
  user_writer_category: { type: DataTypes.STRING(25), defaultValue: 'New member community' },
  user_win_project: DataTypes.INTEGER,
  user_debit: DataTypes.INTEGER,
  user_selling: DataTypes.INTEGER,
  user_saldo_total: DataTypes.STRING(50),
  user_date: DataTypes.DATEONLY,
  user_invoice: DataTypes.INTEGER(255),
  user_yang_ingin_direkrut: DataTypes.STRING(50),
}, { timestamps: false, tableName: 'hrd' });

module.exports = models;
